baseURL = "http://example.org/"
languageCode = "en-us"
title = "WeCoins"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"